language: php
dist: xenial
sudo: required
#addons:
#  apt:
#    packages:
#    - mysql-server-5.7
#    - mysql-client-core-5.7
#    - mysql-client-5.7

php:
 - 5.6

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
